Сб, 21 Сентябрь 2002 17:39 GMT, niggazz сообщил(а):
>ja predlagau zdelat razdel LIMITS.V kotorom budut >opisani vse limiti sushestvuushie v mire,kak ih dostat >i nu cto oni daut,na kokom mobe,kak doiti do nego.

Максимум, что я могу предложить, можно увидеть
[link='http://iclub.nsu.ru/mud/index.pl?section=objects']
здесь [/link]. А что касается того, на каком мобе и как до него дойти, это, imho, черезчур.

Фринн.