Сб, 21 Сентябрь 2002 17:39 GMT, niggazz сообщил(а):
>ja predlagau zdelat razdel LIMITS.V kotorom budut opisani vse limiti sushestvuushie v mire,kak ih dostat i nu cto oni daut,na kokom mobe,kak doiti do nego.
>Vet nekotorie ,tocnee bolshenstvo ludeu ne znau,tocneee redko znaut a sushestvovanii nekotorih limitiv...No a s pomoshu ih je na 49 mozno i na 300dr odetsa))) a trugie to naznaut gde oni lezat ,vot i oblamivautsa....
>

С трудом могу представить себе, как одеться на 300др на 49 уровне, даже уверен что это нереально -). Лимиты для того и нужны чтоб те кто знает могли использовать свое знание, чтоб получить какие-то миимальные плюшки.