Tahikero's pierce misses you. {Плохой кнайт, нет предупредить..Я ж не был готов...}
You yell 'Help! Tahikero is attacking me!'
Tahikero parries your attack.
Your armbands burns Tahikero's face!{ Вот тебе за подлость твою...}
Your burning hands >>> ERADICATES <<< Tahikero.
Tahikero's pierce *** DEVASTATES *** you.
You parry Tahikero's attack.
You parry Tahikero's attack.
The squire fades into existence.
You parry the squire's attack.
The squire's pierce DISMEMBERS you.
You parry the squire's attack.
You blink out the squire's attack.
The squire's pierce MASSACRES you.
You parry the squire's attack.
The squire's pierce MANGLES you.
Tahikero has some small but disgusting cuts.
5211/5591hp 3458/3682m 590/590mv 9am 93%&93%vs83% NESW #
You are affected by the following spells:{Black shroud у меня его как всегда нету}
Spell: protective shield: modifies ac by 20 for 4 hours.
Spell: lich           : modifies race by 77 for 5 hours.
Spell: pass door      : adds 'pass_door' affect for 20 hours.
Spell: slow           : modifies dexterity by -9 for 7 hours.
                      : adds 'slow' affect for 7 hours.
Spell: transform      : modifies hp by 3138 for 17 hours.
Spell: protection good: modifies savingspell by -11 for 11 hours.
                      : adds 'protect_good' affect for 11 hours.
Spell: detect invis   : adds 'detect_invis' affect for 9 hours.
Spell: cloak of leaves: modifies hp by 156 for 5 hours.
Spell: blink          : permanently.
Spell: none           : adds 'flying' affect permanently.
Tahikero has some small but disgusting cuts.
5211/5591hp 3458/3682m 590/590mv 9am 93%&93%vs83% NESW # 
Your crush misses Tahikero.
You parry Tahikero's attack.
Tahikero's a golden sword glows bright blue!
You parry the squire's attack.
You parry the squire's attack.
Tahikero has some small but disgusting cuts.
5211/5591hp 3458/3682m 590/590mv 9am 93%&93%vs87% NESW # 
Tahikero throws a handful of sharp spikes at your feet!
Tahikero's caltrops DISEMBOWELS you.
You start to limp.
Tahikero has some small but disgusting cuts.
5164/5591hp 3458/3682m 590/590mv 9am 92%&92%vs87% NESW # c 'deathen'
You failed.{Ох ты блин..sv самурай}
Tahikero has some small but disgusting cuts.
5164/5591hp 3208/3682m 590/590mv 9am 92%&92%vs87% NESW # 
Your crush misses Tahikero.
You parry Tahikero's attack.
You parry Tahikero's attack.
Tahikero's pierce === OBLITERATES === you.
You blink out Tahikero's attack.
Tahikero's pierce >>> ERADICATES <<< you.
The squire's pierce *** DEMOLISHES *** you.
The squire's pierce MASSACRES you.
You parry the squire's attack.
Tahikero has some small but disgusting cuts.
4397/5591hp 3199/3682m 590/590mv 9am 78%&78%vs87% NESW # af
Your crush misses Tahikero.
You parry Tahikero's attack.
Tahikero's pierce === OBLITERATES === you.
The squire's pierce DISMEMBERS you.
The squire's pierce *** DEMOLISHES *** you.
The squire's pierce DISMEMBERS you.
The squire's pierce MASSACRES you.
Tahikero has some small but disgusting cuts.
3858/5591hp 3199/3682m 590/590mv 9am 69%&69%vs87% NESW # 
The ghost of Piros leaves west.
Tahikero has some small but disgusting cuts.
3858/5591hp 3199/3682m 590/590mv 9am 69%&69%vs87% NESW #
You are affected by the following spells:
Spell: caltrops       : modifies dexterity by -5 permanently. {вот негодяй!!! Как же я драться}
                      : modifies damroll by -5 permanently.   {теперь буду!!!}
                      : modifies hitroll by -5 permanently.
Spell: protective shield: modifies ac by 20 for 4 hours.
Spell: lich           : modifies race by 77 for 5 hours.
Spell: pass door      : adds 'pass_door' affect for 20 hours.
Spell: slow           : modifies dexterity by -9 for 7 hours.
                      : adds 'slow' affect for 7 hours.
Spell: transform      : modifies hp by 3138 for 17 hours.
Spell: protection good: modifies savingspell by -11 for 11 hours.
                      : adds 'protect_good' affect for 11 hours.
Spell: detect invis   : adds 'detect_invis' affect for 9 hours.
Spell: cloak of leaves: modifies hp by 156 for 5 hours.
Spell: blink          : permanently.
Spell: none           : adds 'flying' affect permanently.
Tahikero parries your attack.
Tahikero parries your attack.
A magical hole appears in your shield !
Your shield burns Tahikero's face!
Your torments >>> ANNIHILATES <<< Tahikero.{Такого поворота событий я даже не ожидал}
Your armbands burns Tahikero's face!
Your burning hands >>> ERADICATES <<< Tahikero. {Правильно! Так его! Sanctuary говорят помогает}
You parry Tahikero's attack.
You blink out the squire's attack.
The squire's pierce MASSACRES you.
You parry the squire's attack.
The squire's pierce DISMEMBERS you.
Tahikero is covered with bleeding wounds.
3734/5591hp 3190/3682m 590/590mv 9am 66%&66%vs56% NESW # c weaken
Tahikero looks tired and weak.{ Ты станешь у нас слабым-слабым!}
Tahikero is covered with bleeding wounds.
3734/5591hp 3170/3682m 590/590mv 9am 66%&66%vs56% NESW # c poison
Tahikero parries your attack.
Tahikero parries your attack.
You blink out Tahikero's attack.
You parry Tahikero's attack.
Tahikero's a golden sword glows bright blue!
You blink out the squire's attack.
You parry the squire's attack.
The squire's pierce DISMEMBERS you.
You parry the squire's attack.
The squire's a golden sword glows bright blue!
Tahikero is covered with bleeding wounds.
3670/5591hp 3152/3682m 590/590mv 9am 65%&65%vs58% NESW # 
The ghost of Piros has arrived.
Tahikero is covered with bleeding wounds.
3670/5591hp 3152/3682m 590/590mv 9am 65%&65%vs58% NESW # 
Tahikero looks very ill.{ Ох..а где наши sv...}
Tahikero is covered with bleeding wounds.
3670/5591hp 3142/3682m 590/590mv 9am 65%&65%vs58% NESW # 
Tahikero parries your attack.
Tahikero parries your attack.
You parry Tahikero's attack.
Tahikero's a golden sword glows bright blue!
You parry the squire's attack.
You parry the squire's attack.
You parry the squire's attack.
The squire's a golden sword glows bright blue!
Tahikero is covered with bleeding wounds.
3670/5591hp 3142/3682m 590/590mv 9am 65%&65%vs62% NESW # c plague
Tahikero drops a golden sword.{OH!!! I Like it!}
Tahikero wields his second weapon as first!
Tahikero screams in agony as plague sores erupt from his skin.
Tahikero is covered with bleeding wounds.
3670/5591hp 3122/3682m 590/590mv 9am 65%&65%vs62% NESW # 
Tahikero parries your attack.
Your armbands burns Tahikero's face!
Your burning hands >>> ERADICATES <<< Tahikero.
The tattoo on your shoulder glows blue.
A warm glow passes through you.
Tahikero's slash *** DEMOLISHES *** you.
A katana sword inflicts damage on a violet robe.
You blink out the squire's attack.
You parry the squire's attack.
You parry the squire's attack.
Tahikero is gushing blood.
3540/5591hp 3355/3682m 590/590mv 9am 63%&63%vs46% NESW # c poison
Tahikero drops a katana sword.{GREAT!!! Looks wonderful!!!}
Tahikero looks very ill.
Tahikero utters the words, 'cure critical'.{хмм..}
Tahikero is covered with bleeding wounds.
3540/5591hp 3345/3682m 590/590mv 9am 63%&63%vs50% NESW # 
Your crush misses Tahikero.
Your armbands burns Tahikero's face!
Your burning hands >>> ERADICATES <<< Tahikero.
Tahikero's punch *** DEMOLISHES *** you.
Tahikero's punch MANGLES you.
You parry the squire's attack.
You parry the squire's attack.
You parry the squire's attack.
You parry the squire's attack.
Tahikero is gushing blood.
3318/5591hp 3345/3682m 590/590mv 9am 59%&59%vs38% NESW # c poi

Your crush misses Tahikero.
Tahikero's punch misses you.
You parry Tahikero's attack.
You parry Tahikero's attack.
The squire's pierce MASSACRES you.
The squire's pierce MASSACRES you.
You parry the squire's attack.
You parry the squire's attack.
Tahikero is gushing blood.
3186/5591hp 3345/3682m 590/590mv 9am 56%&56%vs38% NESW # l
Tahikero looks very ill.
Tahikero is gushing blood.
3186/5591hp 3335/3682m 590/590mv 9am 56%&56%vs38% NESW # 
Your crush misses Tahikero.
The tattoo on your shoulder glows blue.
You feel better!
You parry Tahikero's attack.
Tahikero's punch misses you.
You blink out the squire's attack.
You blink out the squire's attack.
You parry the squire's attack.
The squire's a golden sword glows bright blue!
Tahikero is gushing blood.
3302/5591hp 3317/3682m 590/590mv 9am 59%&59%vs38% NESW # 
The ghost of Piros gets Red moss from a big rock.
The Cross Roads
  Here, the great eastern road intersects with an older road between the mines
of Moria and the ruined city of Thalos.  The outskirts of Midgaard lie to your
west, and the highway continues to the east.  An old northern road leads to
the dwarven kingdom and the abandoned mines of Moria, while the southern road
shows the scars of the war which destroyed Thalos.

     A katana sword is forgotten here.
     [.....G.] There is a shiny golden sword on the ground.
     A bunch of pretty wild flowers is here.
[...T...........Felar] The ghost of Piros is here.{ It's my work :)}
[..C.......S....Human] The squire is here, fighting with YOU!.
[...T..R...S....Gold dragon] The golden dragon is here, fighting with YOU!.
[...T.....G.....Human] Tahikero is here, fighting with YOU!.
Tahikero is gushing blood.
3302/5591hp 3317/3682m 590/590mv 9am 59%&59%vs38% NESW # The ghost of Piros eats Red moss.
The ghost of Piros's muscles surge with heightened power.
Tahikero is gushing blood.
3302/5591hp 3317/3682m 590/590mv 9am 59%&59%vs38% NESW # 
Tahikero utters the words, 'cure critical'.
Tahikero is gushing blood.
3302/5591hp 3317/3682m 590/590mv 9am 59%&59%vs41% NESW # 
The ghost of Piros gets Red moss from a big rock.
Tahikero is gushing blood.
3302/5591hp 3317/3682m 590/590mv 9am 59%&59%vs41% NESW # c scourge
The ghost of Piros eats Red moss.
Tahikero is gushing blood.
3302/5591hp 3317/3682m 590/590mv 9am 59%&59%vs41% NESW # 
The ghost of Piros gets Red moss from a big rock.
The gods protect the ghost of Piros.
The squire looks very ill.
The squire appears to be blinded.
The squire looks tired and weak.
Your Scourge of the Violet Spider === ATOMIZES === the squire.
The golden dragon looks very ill.
The golden dragon appears to be blinded.
The golden dragon looks tired and weak.
Your Scourge of the Violet Spider === OBLITERATES === the golden dragon.
Tahikero looks very ill.
Tahikero appears to be blinded.
Your Scourge of the Violet Spider -==> ELECTRONIZES <==- Tahikero.
Tahikero is writhing in agony.
3302/5591hp 3267/3682m 590/590mv 9am 59%&59%vs20% NESW # The ghost of Piros eats Red moss.
Your crush misses Tahikero.
You blink out Tahikero's attack.
You parry Tahikero's attack.
Tahikero yells 'And justice for all!....'{Хмм..хитрый самурай..}
Tahikero screams with a disturbing NOISE!.
The gods protect the ghost of Piros from Tahikero.
3302/5591hp 3258/3682m 590/590mv 9am 59%&NonevsNone NESW # 
The ghost of Piros gets Red moss from a big rock.
3302/5591hp 3258/3682m 590/590mv 9am 59%&NonevsNone NESW #
The ghost of Piros eats Red moss.
3302/5591hp 3258/3682m 590/590mv 9am 59%&NonevsNone NESW # 
The ghost of Piros gets Red moss from a big rock.
3302/5591hp 3258/3682m 590/590mv 9am 59%&NonevsNone NESW # 
The ghost of Piros eats Red moss.
3302/5591hp 3258/3682m 590/590mv 9am 59%&NonevsNone NESW # 
The ghost of Piros gets Red moss from a big rock.
3302/5591hp 3258/3682m 590/590mv 9am 59%&NonevsNone NESW # 
The ghost of Piros eats Red moss.
3302/5591hp 3258/3682m 590/590mv 9am 59%&NonevsNone NESW # c slow tahik
Tahikero starts to move in slow motion.{Очень странный самурай %)) trust all РУЛИТ!} 
Tahikero writhes in agony as plague sores erupt from his skin.
The squire shivers and looks very ill.
Tahikero's sickness injures him.
The squire writhes in agony as plague sores erupt from his skin.
The golden dragon shivers and suffers.
The golden dragon's poison scratches him.
3382/5591hp 3439/3682m 590/590mv 10am 60%&NonevsNone NESW # l

Tahikero utters the words, 'cure poison'.{ты думаешь, это спасение?}
3382/5591hp 3439/3682m 590/590mv 10am 60%&NonevsNone NESW # The Cross Roads
  Here, the great eastern road intersects with an older road between the mines
of Moria and the ruined city of Thalos.  The outskirts of Midgaard lie to your
west, and the highway continues to the east.  An old northern road leads to
the dwarven kingdom and the abandoned mines of Moria, while the southern road
shows the scars of the war which destroyed Thalos.

     A katana sword is forgotten here.
     [.....G.] There is a shiny golden sword on the ground.
     A bunch of pretty wild flowers is here.
[...T...........Felar] The ghost of Piros is here.
[..C.......S....Human] A squire is stands here, with a smile in his face.
[...T..R...S....Gold dragon] A golden dragon is flying here.
[...T.....G.....Human] Tahikero is here, riding the golden dragon.
3382/5591hp 3439/3682m 590/590mv 10am 60%&NonevsNone NESW # 
The ghost of Piros gets Red moss from a big rock.
3382/5591hp 3439/3682m 590/590mv 10am 60%&NonevsNone NESW # c 'power word kill' tahik
The ghost of Piros eats Red moss.
3382/5591hp 3439/3682m 590/590mv 10am 60%&NonevsNone NESW # 
The ghost of Piros gets Red moss from a big rock.
3382/5591hp 3439/3682m 590/590mv 10am 60%&NonevsNone NESW #
The ghost of Piros eats Red moss.
3382/5591hp 3439/3682m 590/590mv 10am 60%&NonevsNone NESW # 
The ghost of Piros gets Red moss from a big rock.
Tahikero yells in panic 'Die, someone, you sorcerous dog!'{ Вот это я люблю больше всего!}
A stream of darkness from your finger surrounds Tahikero.
Tahikero has been killed!
Tahikero's head is shattered, and his brains splash all over you.
