Просто разговор по оос где все прикинулись дурачками )

[Shades of Gray] Gozak: prinimau zakazi na trudnodostavaemoe eq
[Shades of Gray] Derailen: oath ?
[Shades of Gray] Berta: Zedraikis ? :)
[Shades of Gray] Kalagorh: me too
[Shades of Gray] Derailen: nu Zed raikis eto ne trudno )
[Shades of Gray] Gozak: 10 silver per pcs
[Shades of Gray] Berta: Lae Master - soso ?
[Shades of Gray] Derailen: nu pri sootvetstvuyuschem podhode
[Shades of Gray] Berta: zdrenei moshno po odnoi vimanivat
[Shades of Gray] Berta: i flee pri neobhodimosti
[Shades of Gray] Derailen: o, a kak?
[Shades of Gray] Gozak: ya ne mogu po odnoi :(
[Shades of Gray] Gozak: b'u srazu vseh
[Shades of Gray] Berta: streliai po nim :)
[Shades of Gray] Berta: oni pridut sami :)
[Shades of Gray] Derailen: a to ya ih vsegda vsu tolpu valil
[Shades of Gray] Derailen: spasibo za sovet
[Shades of Gray] Berta: srazu v leader'a blast'om strelai
[Shades of Gray] Derailen: a kto iz nih lider?
[Shades of Gray] Derailen: esche bi blast bil ? )
[Shades of Gray] Gozak: da bei vseh, ne zamarachivaisa
[Shades of Gray] Derailen: vot ya o tom je
[Shades of Gray] Berta: da lubim rangovim zaklinaniem strelni po nim
AUCTION: A new item has been received: An oath ring.
[Shades of Gray] Gozak: eto pochti oath
[Shades of Gray] Derailen: BERU !
AUCTION: An oath ring: going once for 100 gold.
[Shades of Gray] Derailen: a mne tut esche govoryat tomagavkami v nih kidatsa
[Shades of Gray] Berta: naskolko ia pomnu Oath beretsya u Zdreni
[Shades of Gray] Derailen: a eto che, ne oath ?
[Shades of Gray] Berta: i ih tam stoit 5 shtuk v komnate ?
[Shades of Gray] Derailen: aga
AUCTION: An oath ring: sold to Derailen for 100 gold.
[Shades of Gray] Derailen: aaaa, Gozak ti menya nae$al !!
[Shades of Gray] Derailen: vozvraschay 1000 golda!
[Shades of Gray] Berta: nu vot ... otkrivaesh komnatu - cast 'magic missile' e.zdreni :)
[Shades of Gray] Berta: i tak po odnoi ubivai
[Shades of Gray] Derailen: a tam je escho do komnati vsakie stoyat
[Shades of Gray] Derailen: oni ne napdut?
[Shades of Gray] Berta: vrode ne napadaut
[Shades of Gray] Derailen: ok ya shas poprobuyu
[Shades of Gray] Derailen: aaaa ubivayut !!! Gozak sumon me !! ma menya vse zdreni kinulis!!
[Shades of Gray] Berta: mda ..
[Shades of Gray] Berta: vse - eto kakie ?
[Shades of Gray] Derailen: nu tam kakoyto zdreni stileto - on mne takoy bs vstavil
[Shades of Gray] Berta: uuu ...
[Shades of Gray] Berta: a ti imp_invis proboval veshat ?
[Shades of Gray] Derailen: ne, ya ego po  moemy ne zaprakal escho
[Shades of Gray] Berta: mda ...
[Shades of Gray] Berta: detect_hide skushai
[Shades of Gray] Derailen: a gde ego vzat' ?
[Shades of Gray] Berta: detect_hide skushai ...
[Shades of Gray] Berta: cast summon herbalist helper
[Shades of Gray] Berta: vrode u nego est puchok travi
[Shades of Gray] Derailen: o, trava eto tema
[Shades of Gray] Derailen: You failed.
[Shades of Gray] Berta: nu togda dui v Great Gerighelm
[Shades of Gray] Derailen: ne, tuda ya bolshe ne poidu .. tam kakoy-yo protector zloy sidit
[Shades of Gray] Derailen: on menya v raund urabotal
[Shades of Gray] Berta: eto vroder clanguard kogo-to ...
[Shades of Gray] Berta: a ne mob :)
[Shades of Gray] Derailen: a che, clanguardi ne mobi ?
[Shades of Gray] Berta: mobi :)
[Shades of Gray] Berta: dik nax ti k nemu shel ?
[Shades of Gray] Derailen: nu iskal travu
[Shades of Gray] Berta: uuu ...
[Shades of Gray] Berta: ti ne znaesh gde tam trava ?
[Shades of Gray] Derailen: v kakom-to samu vrode?
[Shades of Gray] Gozak: kto zedrakis zakazival?
[Shades of Gray] Gozak: berite
AUCTION: A new item has been received: a honed shortsword 'Zedraikis'.
[Shades of Gray] Berta: mda ... zedraikis na 7 levele :)
[Shades of Gray] Gozak: ya shkuroi riskoval! men'ya tam stabili!
[Shades of Gray] Gozak: The Laerkai Master's backstab === OBLITERATES === you.
[Shades of Gray] Gozak: nu che tam s avengerami?
[Shades of Gray] Derailen: vsyo, vse 6 umerli

[Shades of Gray] Derailen: mlya karoche .. ya shas so smeha ussus' ))
