Для начала хочу всем сообщить что Muwa Sayonara i Tara
-один человек :)))
(После просмотра лога Дерайлена) Тара может нам еще спасибо сказать что ты возжелала вступить к нам в клан? мля я такой наглости и манчкинства давно не видел, сам когда 1 квест делал бегал 3 недели (я тогда тут один ночами сидел, вот и бегал почти каждую ночь  за этим посохом), 2 тоже долбал долго умирал хрен знает скока (на 50 лвле в ближнем бою надо было положить саранчу(91 лвл моб) и пройти колодец), а ты мля хочешь нахаляву, у тебя уже Мува в Рыцарях и Сай в БРах може хватит???
Ну и вот еще один лог:
Сказ о том как умный некрос и страшный тролль развели трусливую самуршу-мульта:
Предисловие:
566hp 2049m 508mv Opp:None NED # tell tar Say privet peredavay kstati
You tell Tara 'Say privet peredavay kstati'

566hp 2049m 508mv Opp:None NED # 
Tara tells you 'ona spat poydet cherez polchasa, shas v dushe'

566hp 2049m 508mv Opp:None NED # 

780hp 2210m 508mv Opp:None NED # tell ta a ti kto ey?
You tell Tara 'a ti kto ey?'

780hp 2210m 508mv Opp:None NED # 
Tara tells you 'po obshage odnokomnatnica'
а теперь сама сказка(где то через несколько часов, Сай уже типа 5 сон видит )
Tara tells you 'malin'(Тара в игре, я левелюсь)
далее:
[Shades of Gray] Derailen: nu che, idem na powera?(Дера и Чулбурк уже порайдили БРов втихую)
[Shades of Gray] Derailen: ops, miss(развод начался, в общем то без цели выманить и убить Сай просто так скорее)
[CLAN] Goris: eto ti MNE?
[Shades of Gray] Chulburk: nu ja neznay 
[CLAN] Derailen: eto provokaciya
[CLAN] Goris: ???
[CLAN] Goris: aa...
[CLAN] Goris: :)
[CLAN] Goris: na CHTO??na reraid?
[CLAN] Derailen: nu sayonaru summonim
[Shades of Gray] Chulburk: br'ov net?
[Shades of Gray] Goris: Chulburk ya haste kinu..ayda s nami BRov gonyat(вроде как пытаюсь поучавствовать)
Chulburk tells you 'uje....'
[Shades of Gray] Derailen: da chul vse portit 
Chulburk tells you 'sayorary vimanivaem'
You tell Chulburk 'da znayu ya :)'
[Shades of Gray] Chulburk: ey~ooc ey!
[Shades of Gray] Chulburk: ladno vse idem.....
[Shades of Gray] Chulburk: Der blat rescu!!!!! 
[Shades of Gray] Derailen: idu
[Shades of Gray] Chulburk: suka  CRITIKAL!!!!
who
Following persons are traveling in Shades of Gray:
     Sayonara, the Ancient Battle Mistress.<---а вот и оно пришло, думая что итем еще на месте и расчитывая порвать Деру пока Повермэн жив
     Stroggorn
     Chulburk
     [Shalafi] Derailen
     Tazel
[PK] Zion
[PK] [Shalafi] Goris
[CLAN] Derailen: SUPER !!!!!!!!!!!!!
[Shades of Gray] Chulburk: flee.....
[Shades of Gray] Derailen: flee, Say zashla
[Shades of Gray] Sayonara: tolku to
[CLAN] Goris: provotsiruy ee na reraid..mi obstrell ey so spini sdelaem
[CLAN] Goris: budet reraid a?
[Shades of Gray] Derailen: eh ona quit ) <---Какая жалость :) итема то нет :) остается только героически умереть(на что Сай явно неспособна), Сай, теперь когда ты будешь вопить что я трус не вступаю в ближний бой с 2 БРами на 30 лвлов выше себя я ткну тебя носом сюда
[Shades of Gray] Chulburk: SAyonara......kis...kis...
[Shades of Gray] Chulburk: idi poceluy menya
[Shades of Gray] Derailen: Tara zamette vishla .. tipa pitaetsa ne sovsem narushat' zakon o multikah )
[Shades of Gray] Goris: da her...ona toka mojet ponti kidat peredo mnoy kogda ya nije na 30 lvl chem ona
[Shades of Gray] Goris: i vse..pered ostalnimi ona tikaet v gildiyu ili quit
[CLAN] Derailen: mlya popalas na prostoy razvod )




