
hp 2224m 529mv Opp:None UD # c slow gole
An iron golem starts to move in slow motion.
An iron golem's pound DISMEMBERS you.
An iron golem is in perfect health.

hp 2194m 529mv Opp:100% UD # c fireba go <---пошел спамить :))

An iron golem dodges your attack.
You parry an iron golem's attack.
An iron golem tries to disarm you, but fails.
An iron golem is in perfect health.

hp 2194m 529mv Opp:100% UD # c fireba go
Your fireball === ATOMIZES === you.
An iron golem is in perfect health.

hp 2169m 529mv Opp:100% UD # c fireba go

Your slice MASSACRES an iron golem.
Ciquala's sword draws life from an iron golem.
Your slice MASSACRES an iron golem.
Ciquala's sword draws life from an iron golem.
An iron golem's pound DISEMBOWELS you.
An iron golem has a few scratches.

hp 2169m 529mv Opp:96% UD # Your fireball === ATOMIZES === you.
An iron golem has a few scratches.

hp 2144m 529mv Opp:96% UD # c fireba go <--- глянул на экран, но....поздно

Your slice MASSACRES an iron golem.
Ciquala's sword draws life from an iron golem.
An iron golem's pound DISMEMBERS you.
An iron golem has a few scratches.

hp 2144m 529mv Opp:94% UD # Your fireball === ATOMIZES === you.
You sure are BLEEDING!
An iron golem has a few scratches.

hp 2119m 529mv Opp:94% UD # flee

An iron golem dodges your attack.
You parry an iron golem's attack.
An iron golem has a few scratches.

hp 2119m 529mv Opp:94% UD # ca 'improved invis'

An iron golem has a few scratches.

hp 2217m 532mv Opp:95% UD # Your fireball -==> ELECTRONIZES <==- you.
You have been KILLED!!

